---
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu noses
    apt:
      name: "{{myjavapackonubntu}}"
      state: present
    when: ansible_os_family=="Debian"   

  - name: install java on redhat nodes
    dnf:
      name: "{{myjavapackonredHat}}"
      state: present
    when: ansible_os_family=="RedHat"  