---
- hosts: 10.2.0.7
  become: yes
  tasks:  
  - include_tasks: myfile.yml
  - name: i want create a folder
    file:
      path: /home/rajuammu/myfolder
      state: touch

  - name: i want to copy a file
    copy:
      src: mystaticfile  
      dest: /home/rajuammu/ 


  - name: i want to install apache2
    apt:
      name: apache2
      state: present    