---
- hosts: 10.2.0.7
  become: yes
  tasks:
  - name: install git 
    apt:
      name: git
      state: present
    tags: mygit 

  - name: install tree
    apt:
      name: tree
      state: present
    tags: mytree 

  - name: install wget
    apt:
      name: wget
      state: present
    tags: mywgit  