- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ansible nodes
    apt:
      name: apache2
      state: present
    when: ansible_os_family=="Debian"  

  -name: start webserver
    apt:
      name:  wget
      state: present
    when: ansible_os_family=="Debian"  