- hosts: mywebserver
  become: yes
  gather_facts: yes
  tasks:
  - name: install webserver on ubuntu ansible nodes
    apt:
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family=="Debian"  

  - name: start webserver
    service:
      name:  "{{mywebpackonubuntu}}"
      state: started
    when: ansible_os_family=="Debian"  

  - name: install webserver on RedHat ansible nodes
    dnf:
      name: "{{mywebpackonredhat}}"
      state: present
    when: ansible_os_family=="RedHat"  

  - name: start webserver on RedHat
    service:
       name: "{{mywebpackonredhat}}"
       state: started
    when: ansible_os_family=="RedHat"    